---
name: module4_task1

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
      - "master"
    tags:
      - "v*.*.*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install required tools
        run: cd module4_task0 && sudo ./setup.sh

      - name: Unit test
        run: sudo make unit-tests -C module4_task1

      - name: test2
        run: sudo make integration-tests -C module4_task1

      - name: validate
        run: sudo make validate -C module4_task1

      - name: help
        run: sudo make help -C module4_task1

      - name: Build command
        run: sudo make build -C module4_task1

      - name: Build docker
        run: sudo make build docker -C module4_task1

      - name: package
        run: sudo make package -C module4_task1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module4_task1/DEPLOY.md
            module4_task1/awesome-website.zip
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './module4_task1/dist'
          production-branch: main
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "ðŸŽ‰ Published on"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
...
